### ISSUE TITLE
Level editor - Re-save all tiles crash

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#10]
**Describe the bug**
Clicking on "Re-save all tiles" without active map crashes the level editor.

**To Reproduce**
1. Start the level editor
2. Close the "Open level" welcome screen.
3. Click in the menu on Tools
4. Click on Developer > 
5. Click on Re-save all tiles

**Expected behavior**
Some popup saying that nothing is active maybe?

**Screenshots**
![LevelEditor_2021-12-03_21-50-29](https://user-images.githubusercontent.com/50502395/144671284-909816a9-900c-408b-850a-e28f1a88a1f1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, 10.0.19043
 - Version: SVN_7272.TC_4884 dx11

**Comment by lukaasm** [comment]
SELF-NOTE: should be enabled only if workspace is "Development"
