### ISSUE TITLE
Level Editor - Prefab culling type -> none

### ISSUE THREAD

**Issue by Molch1** [exorstudios/riftbreaker-tools#103]
**Is your feature request related to a problem? Please describe.**
In some cases/for certain structures it would be nice if prefab culling could be deactivated.

**Describe the solution you'd like**
New option in culling type list -> disabled

**Comment by lukaasm** [comment]
How would that work?

![image](https://user-images.githubusercontent.com/48881/185702433-e128c5e3-72d3-4eba-9594-4a22e8d699ee.png)

Culling mode in that case means: How to determine if a prefab object can be spawned on terrain.

- pivot: green point ( object centre ) must be within the prefab mask zone
- collision: whole object must be within the prefab mask zone

- none? If any part of object touches prefab mask zone, then spawn it?

**Comment by Molch1** [comment]
Thank you for the explanation! I misunderstood and thought culling type was affecting entities overlapping within masked area since I was stacking them and they were deleted - issue #170
