### ISSUE TITLE
ERROR: failed to load system font face: `Microsoft YaHei UI`

### ISSUE THREAD

**Issue by 1971580185** [exorstudios/riftbreaker-tools#108]
ERROR: failed to load system font face: `Microsoft YaHei UI`

Trace:
(filename not available):0 - void __cdecl Exor::Abort(char const * __ptr64,struct spdlog::source_loc,bool)
(filename not available):0 - struct ImFont * __ptr64 __cdecl ImGui::LoadSystemFonts(float,float)
(filename not available):0 - public: void __cdecl ImGui::PlatformBackend::Initialize(class Editor::ImGuiWindow
 * __ptr64) __ptr64
(filename not available):0 - protected: virtual void __cdecl Editor::Application::OnRenderingAccessAcquired(vo
id) __ptr64
(filename not available):0 - public: class Exor::RenderingState * __ptr64 __cdecl Exor::BaseFrameworkState::Tr
yAcquireRenderingAccess(void) __ptr64
(filename not available):0 - protected: virtual void __cdecl Editor::Application::OnUpdate(float) __ptr64
(filename not available):0 - protected: virtual void __cdecl Exor::AppState::Update(float) __ptr64
(filename not available):0 - public: void __cdecl Exor::AppMsm::Update(float) __ptr64
(filename not available):0 - public: void __cdecl Exor::Framework::Update(float) __ptr64
(filename not available):0 - protected: virtual void __cdecl Editor::Application::OnTick(float) __ptr64
(filename not available):0 - public: virtual int __cdecl Exor::ApplicationAbstract::Run(void) __ptr64
(filename not available):0 - int __cdecl Exor::RunApp(class Exor::ApplicationArgs const & __ptr64,class Exor::
ApplicationAbstract * __ptr64)
(filename not available):0 - WinMain
(filename not available):0 - __scrt_common_main_seh
(filename not available):0 - BaseThreadInitThunk
(filename not available):0 - RtlUserThreadStart

**Comment by STAR-KY-XH** [comment]
Need to fix, many Chinese players are unable to use the latest editor because of this problem
