### ISSUE TITLE
Model editor - Wrong saving hierarchy for att_ files

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#109]
**Describe the bug**
The model editor can look at the skeleton and view the att_ nodes, change their placement and save it - but saving doesn't actually do anything.

**To Reproduce**
1. Open model editor
2. Move around some att_ nodes in some skeleton
3. Save
4. Test if it changed

**Expected behavior**
Actually saving the new att_ positions to the game files

Tools version 4950

**Comment by SenorRagequit** [comment]
Workaround by Łukas:

![grafik](https://user-images.githubusercontent.com/50502395/172023435-4bd03838-bf97-42bf-9851-010619defa24.png)

**Comment by lukaasm** [comment]
Should be fixed?

**Comment by SenorRagequit** [comment]
> Should be already fixed?

Is fixed
