### ISSUE TITLE
Riftbreaker editor - Show patch value changes

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#111]
Something very handy for bug testing and wiki management would be an overview of things that changed in the latest patch compared to the current game files.

Currently, you might see new/changed files inside the new patch zip, like 11_win_data.zip > entities > units > ground > bitrid.ent
But you don't know what actually changed inside that file.

So it would be cool if there would be some value checker that checks what valued changed and just lists them plain and simple.
Like:

| Bitrid.ent - Value | Old | New |
| ------------- | ------------- |------------- |
| Health  | 250 | 300 |
| aggressive_speed  | 14  | 17 |
|  |  |  |
| Bitrid_alpha.ent - Value | | |
| Health  | 250 | 300 |
|  |  |  |
| Bitrid_ultra.ent - Value | | |
| aggressive_speed  | 18  | 14 |

It would take the latest zip and compare it against the unified collection of the other zips (like the left side of the workspace editor)

**Comment by lukaasm** [comment]
#5 Linking to 5, the workspace editor should have a selectable "GameVersion" for comparison in CompareWorkspaces

```
GameFiles
 - GameFiles 02
 - GameFiles 01
 - GameFiles 00
 ```
