### ISSUE TITLE
Add a button to start The Riftbreaker from withing the editor

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#120]
### Enter your feature description.

Instead of having to open up the Riftbreaker manually each time, add a button to the Workspace Editor which starts the game for you.

1) Should take into account that there is Steam + other ways to have the game
2) Would be coooolest if there would be a settings menu for that button where you can set the mission. So it might auto join a sandbox map or join the test_full_base map or whatever it was called.

**Comment by lukaasm** [comment]
![image](https://user-images.githubusercontent.com/48881/185806814-4e191710-4820-4578-9312-7aadd8b601de.png)
