### ISSUE TITLE
Workspace file filter ignored

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#123]
### How are you using the tools?

Steam

### Enter your bug description.

When using the file filter for the right side of the workspace, the results don't change, as if the filter is getting ignored.
![grafik](https://user-images.githubusercontent.com/50502395/173236839-ca66a6ca-0e8a-4643-b336-1c8e4e1bba74.png)

### How can this bug be reproduced?

Get some files with different names, then filter at the top

### Tool version

TC_4950

**Comment by SenorRagequit** [comment]
@lukaasm Not fixed

![grafik](https://user-images.githubusercontent.com/50502395/187022213-73bfd5f5-83b1-44e6-9273-fbdadddf5148.png)

**Comment by lukaasm** [comment]
You are matching against: the `scripts` substring which every file shown here begins with.

Filter matching works against whole path to the file, so if you wrote `research` you would get everything from scripts/research subtree

**Comment by SenorRagequit** [comment]
> You are matching against: the `scripts` substring which every file shown here begins with.
> 
> Filter matching works against whole path to the file, so if you wrote `research` you would get everything from scripts/research subtree

I am actually just stupid. I thought research is on the same file depth as scripts. I didn't see it is inside of scripts.
Oh mah gawd in heaven
