### ISSUE TITLE
Use Enter key as confirmation in various ways

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#147]
### Enter your feature description.

A small QoL/UX improvement would be to use Enter as a confirmation button in more GUI elements.
Example: You create a new workspace, type in the name and just hit enter to confirm.
![grafik](https://user-images.githubusercontent.com/50502395/176946672-7ffee23a-79ca-4354-aae7-6d272f36bb2b.png)

Currently, you have to use the mouse to click on "Create".

There are probably more ways to use the Enter key, might as well use if wherever possible to enhance the UX.

**Comment by lukaasm** [comment]
I have added Enter key support to some dialogs but you can paste here all dialogs where you would like to see it work.

**Comment by SenorRagequit** [comment]
Could be added here too:
![grafik](https://user-images.githubusercontent.com/50502395/186216546-158ecb7e-3ff9-4b21-ab6d-d26fa44d3e52.png)

**Comment by lukaasm** [comment]
I wonder what Enter accept here.
Good practice tells, that non-destructive action should always be focused by default

**Comment by SenorRagequit** [comment]
@lukaasm Add Enter as "accept" to the new "Copy as..." too.
Currently, if you press Enter 2x in that gui window, it just closes.

**Comment by lukaasm** [comment]
fixed, Enter by mistake starter working as Cancel :P
