### ISSUE TITLE
Allow mesh height change so weapons aren't underground

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#153]
### How are you using the tools?

Steam

### Enter your bug description.

Using the model editor to look at weapons and place _atts seems pretty wild, since you can't really see anything opening them up.
![grafik](https://user-images.githubusercontent.com/50502395/178965325-ade39673-5a05-4ff8-b121-0ea4360f7647.png)

So either allow us to move meshes (at least in height) or fix weapons/enitites spawning below the ground

### How can this bug be reproduced?

Open a weapon, like the burst_rifle in the picture

### Tool version

TC_4950

**Comment by lukaasm** [comment]
![image](https://user-images.githubusercontent.com/48881/178969502-52e17b55-a5b6-432e-89e5-85cf5ed44573.png)
Just hide the floor?

**Comment by SenorRagequit** [comment]
>
