### ISSUE TITLE
Decorations disabling unit volumes

### ISSUE THREAD

**Issue by Molch1** [exorstudios/riftbreaker-tools#157]
### How are you using the tools?

Steam

### Enter your bug description.

Decorations placed in Level Editor will prevent **boss, liquid, neutral, regular** and **resource unit volumes** within a radius of ~ 1 tile from working/spawning, while specific unit volumes do.
![deco01](https://user-images.githubusercontent.com/97815025/181109186-f7a220d4-70b0-4fd4-9279-b11ea91c7564.png)

![deco_delete02](https://user-images.githubusercontent.com/97815025/181109836-833f8013-e4c9-43aa-8a04-46c3325490a3.png)
![deco03](https://user-images.githubusercontent.com/97815025/181110734-33db67e3-0f51-433e-a76e-8c552581fbf6.png)
![deco04](https://user-images.githubusercontent.com/97815025/181110886-3483efcc-48bd-4913-878a-81a2c5fef6cb.png)

So you can´t really use decorations in Level Editor which is unfortunate, since they are not available as props like alien structures for example.

### How can this bug be reproduced?

1. Place a decoration 
2. Place boss, liquid, neutral, regular or resource unit volume around it
3. Jump in game - unit volumes within ~ 1 tile radius of decoration won´t spawn units

### Tool version

TC_4950

**Comment by lukaasm** [comment]
It's how the spawn system was designed. 
But I will try to come up with solution how to allow to override default spawn rules.

**Comment by Molch1** [comment]
That would be great, thank you!

**Comment by Molch1** [comment]
can just use own “prop” version of decorations or team “neutral” to circumvent
