### ISSUE TITLE
Randomize scale uniformly

### ISSUE THREAD

**Issue by Molch1** [exorstudios/riftbreaker-tools#162]
### Enter your feature description.

A nice addition would be if we could randomize scale uniformly,
maybe with a uniform checkbox in randomize scale window.
![randomize scale uniform](https://user-images.githubusercontent.com/97815025/183308286-f5a8134b-66cc-43eb-b63f-2008e688d1ca.png)

**Comment by lukaasm** [comment]
![image](https://user-images.githubusercontent.com/48881/185493297-5e848071-01bd-4c70-b12c-645fd046a0ee.png)
![image](https://user-images.githubusercontent.com/48881/185493350-fbbc8a9f-fa4c-47d4-8994-c3db8e17d114.png)

Support for constraining any combination of axes
