### ISSUE TITLE
Scaling in one direction

### ISSUE THREAD

**Issue by Molch1** [exorstudios/riftbreaker-tools#167]
### Enter your feature description.

Having the option to scale only in one direction of axis, not both at the same time, would be nice.

**Comment by lukaasm** [comment]
Dev level editor currently has "new" gizmos implementation with new resize mode:
![resize-gizmo](https://user-images.githubusercontent.com/48881/185762142-97dccae3-87fe-48b4-aea0-49fa6532a8fd.gif)

Will it satisfy this request?

**Comment by Molch1** [comment]
Absolutely :D
