### ISSUE TITLE
Copy file name & file path

### ISSUE THREAD

**Issue by Molch1** [exorstudios/riftbreaker-tools#168]
### Enter your feature description.

A copy file name & copy file path option in the right click menu of Workspace Editor would be great!

So you can quickly paste them in a file, for example, when trying out different particle effects, materials, etc.

**Comment by lukaasm** [comment]
![image](https://user-images.githubusercontent.com/48881/185486877-0b07eae1-b1e6-4371-bdd8-f150e683b8bb.png)
