### ISSUE TITLE
Only generate currently opened tile

### ISSUE THREAD

**Issue by Molch1** [exorstudios/riftbreaker-tools#172]
### Enter your feature description.

When jumping in game via play button an option to only load/generate the currently opened tile in Level Editor would be very nice, especially if you already have several tiles defined in mission file. So you don´t have to comment them out, change spawn ratio or search the tile in map, but can directly spawn in desired tile for testing.

Suggestion: add option here:
![Play_game_window](https://user-images.githubusercontent.com/97815025/185760911-da4a8245-17e1-49d7-a730-22cb6d356d3e.png)

**Comment by lukaasm** [comment]
We have already implemented that:
![image](https://user-images.githubusercontent.com/48881/185761581-1ff7c94e-c577-40b9-b4a2-a05d8691208d.png)

checking `Use only this tile` will force mission map generator to fill map with this one
