### ISSUE TITLE
Favorites Tab

### ISSUE THREAD

**Issue by Molch1** [exorstudios/riftbreaker-tools#174]
### Enter your feature description.

A favorites tab would be helpful - you can put/link all your most needed entities there for quick access (without showing folder structure). Logic entities, resource/random/unit volumes, for example.

**Comment by lukaasm** [comment]
![image](https://user-images.githubusercontent.com/48881/186645177-5bd8986f-4f81-423a-929d-aa642edd6bfd.png)
Hovering over blueprint will show pin/unpin button
