### ISSUE TITLE
[0.2.5205-pre] General feedback

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#180]
Some general collected feedback for this release:

- Performance seems to have improved, especially the mission editor seems much smoother now
- The icon to set a workspace as active seems confusing. At least I don't know what a megaphone has to do with setting a workspace active. 
![grafik](https://user-images.githubusercontent.com/50502395/186214325-6747c05e-3495-4586-8307-feddfe6d1ef4.png)

- The tooltip you get when having bad syntax for a name is bad. I thought it would include the ! as a symbol, but it's the ! from the sentence. Maybe add a gap or remove it. Currently it looks like the ! is part of the accepted symbols.
![grafik](https://user-images.githubusercontent.com/50502395/186214738-cc1ffb81-1664-426d-8121-e006bfba47b3.png)

- The first entry of the mod manager doesn't really show that it's a button and not a mod called "Mods". Needs some love, like "Select/Deselect all mods" and then some visual indicator.
![grafik](https://user-images.githubusercontent.com/50502395/186215358-5df0ea1f-187d-4b2a-93a3-330d7371e216.png)

**Comment by lukaasm** [comment]
![image](https://user-images.githubusercontent.com/48881/186229449-6c0fb6f4-26f8-470a-8a3a-fdaf9e930191.png)

Maybe star? :P
![image](https://user-images.githubusercontent.com/48881/186229527-45fe1744-4e95-48e1-97a6-9b5b9c0e3da2.png)

![image](https://user-images.githubusercontent.com/48881/186229598-195c6549-551d-45c5-a943-a59e1d90c10f.png)

**Comment by SenorRagequit** [comment]
Instead of the star, how about a checkmark icon which has that modern-UI effect of dark vs bright.
![grafik](https://user-images.githubusercontent.com/50502395/186245648-254849d7-2ddd-498c-aea5-b0f703d27c2a.png)

**Comment by SenorRagequit** [comment]
Issue not valid anymore
