### ISSUE TITLE
Rename files confirmation button uses wrong text

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#181]
### How are you using the tools?

Github download

### Enter your bug description.

The confirmation button for the "rename files" UI is wrong, it says "Create" while it should probably say "Rename"
![grafik](https://user-images.githubusercontent.com/50502395/186216299-8d8fb131-e7be-4d91-9263-0d328f1e3b51.png)

### How can this bug be reproduced?

Rename a file

### Tool version

TC_5205

**Comment by lukaasm** [comment]
I knew you would report that :P No laziness goes unpunished!

**Comment by SenorRagequit** [comment]
Not actually fixed in TC_5221
![grafik](https://user-images.githubusercontent.com/50502395/187214970-1b2bc19b-34b7-46c2-bf9e-3fe37f89dc00.png)

But you might just forgot to push the change.
