### ISSUE TITLE
Use Escape key as abort in various ways

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#182]
### Enter your feature description.

Similar to #147 , use the Escape key on the keyboard as the abort key, as if you would close a window top right via the X.

Should be available for every small in foreground window like:

- 

![grafik](https://user-images.githubusercontent.com/50502395/186217215-184e4aeb-f03a-4323-8fe6-9e393f42f08c.png)

-

![grafik](https://user-images.githubusercontent.com/50502395/186217264-a6d1dce2-92aa-473a-96e2-b3cc9b2f9468.png)

- 

![grafik](https://user-images.githubusercontent.com/50502395/186217548-cbb1fb91-0e6b-4591-bf91-dfabf1a96750.png)

-

![grafik](https://user-images.githubusercontent.com/50502395/186217815-ee43a271-74f4-4db1-9f10-0b6364456d52.png)

**Comment by lukaasm** [comment]
all dialogs will be now dismissable by Escape
