### ISSUE TITLE
Window buttons unusable

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#197]
### How are you using the tools?

Github download

### Enter your bug description.

Sometimes the workspace window buttons (minimize, maximize, exit) get unusable.
Sometimes you can at least highlight them, sometimes they don't even highlight anymore when hovering with the mouse over them.
Video of the bug: https://streamable.com/zt2abk

### How can this bug be reproduced?

No idea tbh. 

### Tool version

TC_5206

**Comment by lukaasm** [comment]
Some work was done to fix this, does it still occur?

**Comment by SenorRagequit** [comment]
> Some work was done to fix this, does it still occur?

No, is fine with current steam version
