### ISSUE TITLE
Crash by playtesting

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#200]
### How are you using the tools?

Github download

### Enter your bug description.

Got a crash by playtesting a level I made.
The crash error seems a bit weird, so I don't know if it's a crash because my map is just somehow wrong or a crash because there is  a bug somewhere.

![grafik](https://user-images.githubusercontent.com/50502395/187030934-c4c9a650-8b22-44e0-8f2b-fab3e27b8a54.png)

I sent a crash report linking to this issue

### How can this bug be reproduced?

No idea what caused it

### Tool version

TC_5206

**Comment by lukaasm** [comment]
Tools are using never binary serializer than game on Steam, I need to downgrade it until new Riftbreaker update is release
