### ISSUE TITLE
All editors - Show list of current hotkeys

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#203]
### Discussed in https://github.com/exorstudios/riftbreaker-tools/discussions/29

<div type='discussions-op-text'>

<sup>Originally posted by **SenorRagequit** December  4, 2021</sup>
What are the current level editor hotkeys?
Is there a file one could look in to?

I don't want to feature request hotkeys which are already given 🚀 </div>

As brought up in one of the old discussions, we need a menu item which can show us the hotkeys for every editor.
Like:
![grafik](https://user-images.githubusercontent.com/50502395/187090905-2db2e1c0-acbb-4622-b128-150a1f82ff9b.png)

**Comment by lukaasm** [comment]
![image](https://user-images.githubusercontent.com/48881/187223771-e650a3b5-3355-47e4-8ade-424a7d01de7d.png)
![image](https://user-images.githubusercontent.com/48881/187223811-5e52232d-10a8-44f1-8281-57b9fd9299a8.png)
For now you will get 'raw' dialog version in Editor>Preferences>Settings

No descriptions, just action name, arg, and keys :P

I will later expand upon Settings dialog
