### ISSUE TITLE
Play game - Save starting config

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#217]
### Enter your feature description.

When starting the game through the WS editor, it should save my last used configuration, so I don't have to enter it over and over again.
![grafik](https://user-images.githubusercontent.com/50502395/188205562-32ad2329-1dc7-4f34-83db-842a1d6819bc.png)

**Comment by SenorRagequit** [comment]
@lukaasm 
Something like this would be great:
![grafik](https://user-images.githubusercontent.com/50502395/205267322-e5fbe2ef-b6a1-43e1-976e-414d92ad5e3b.png)

So the play button is "cut" where the left side shows a gear icon where the settings can be configured and saved.
And the play button just starts the game with that config, no more asking for stuff.

**Comment by lukaasm** [comment]
<img width="342" alt="image" src="https://user-images.githubusercontent.com/48881/205399844-ec65071d-8f90-4ef7-a532-8039808922ca.png">
