### ISSUE TITLE
Allow better control in input boxes

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#218]
### Enter your feature description.

All editors?

The input box like here:
![grafik](https://user-images.githubusercontent.com/50502395/188216659-df5827ca-3b4f-4c90-97a8-6a99650c0299.png)

Doesn't allow moving left - right with the arrow keys, and not even the delete key is working.
![grafik](https://user-images.githubusercontent.com/50502395/188216756-78f98d89-f87c-4155-aea5-fe6c3af8122d.png)

**Comment by lukaasm** [comment]
Works fine now?

**Comment by SenorRagequit** [comment]
> Works fine now?

Fixed
