### ISSUE TITLE
All editors - Performance menu

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#229]
My GPU starts up like a jet trying to push out 700+ fps in the editors (especially model editor) and it becomes really annoying.
So we could need some small performance menu which can set the graphic / limited fps like we have in The Riftbreaker

**Comment by lukaasm** [comment]
For now try to set in config:

```
set r_max_fps 30
```

or in console:
```
r_max_fps 30
```

**Comment by lukaasm** [comment]
Some things related to performance and over-delivering were changed and editors should not try to fly to the moon using your card

**Comment by lukaasm** [comment]
<img width="676" alt="image" src="https://user-images.githubusercontent.com/48881/205721565-3656a5ea-4f73-41e5-a0cc-c4886218b38e.png">
Time for proper settings menu!
