### ISSUE TITLE
Clone file

### ISSUE THREAD

**Issue by Molch1** [exorstudios/riftbreaker-tools#235]
### Enter your feature description.

A clone/duplicate file function in right click menu would be nice.

(maybe clone & rename - after cloning rename menu shows up to immediately rename file)

So you can quickly duplicate & rename a file you made changes to and then want to make variants out of.

**Comment by SenorRagequit** [comment]
@lukaasm Isn't this feature already public now?
![grafik](https://user-images.githubusercontent.com/50502395/202563980-c72791ea-cd30-47cc-9c68-c901da926dcf.png)

**Comment by lukaasm** [comment]
it is ;p
