### ISSUE TITLE
Add an option to start with cheats

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#238]
### Enter your feature description.

Especially for testing it would be suuuuper handy if this window here:
![grafik](https://user-images.githubusercontent.com/50502395/193067202-11c7e2d9-d52b-45f4-9152-369a42b25160.png)

Could get 3 checkboxes which activate these
![grafik](https://user-images.githubusercontent.com/50502395/193067340-6b6e7e87-02e6-4772-821d-2918de6233f9.png)
cheats in the game.
So you can directly start with cheats enabled.
The values should be saved so I don't always have to re-check those checkboxes of I want to test something quickly.

**Comment by lukaasm** [comment]
![image](https://user-images.githubusercontent.com/48881/205403666-a380f610-2e81-4c85-93ba-8ff43c55498b.png)
