### ISSUE TITLE
Tag "skin" becomes tag "items"

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#243]
### How are you using the tools?

Steam

### Enter your bug description.

Uploaded my mod as "skin" but in game it's called "items"
![grafik](https://user-images.githubusercontent.com/50502395/201982356-7624a3b1-229b-4daf-a3ea-eaca9171bb18.png)
![grafik](https://user-images.githubusercontent.com/50502395/201982400-ad83bf93-9a7c-4c53-b347-351862e586b2.png)

### How can this bug be reproduced?

Upload as skin

### Tool version

TC_5350

**Comment by SenorRagequit** [comment]
Error is probably this:
![grafik](https://user-images.githubusercontent.com/50502395/202028092-39f6bdda-47f1-4e29-aabd-68f97ad73713.png)

**Comment by lukaasm** [comment]
Nah, issue is prolly with refreshing tags in details tab. I believe u had previously selected mod with Items tag, and selecting another mod with only one tag didn;t refresh view properly
