### ISSUE TITLE
Mission editor - Crash on "Start game from this start point" button

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#25]
**Describe the bug**
When clicking the button "Start game from this point" without anything but the start event, the mission editor crashes.

**To Reproduce**
1. Create new mission
2. Click on "Start game from this point" arrow at the first event
3. Crash

**Expected behavior**
A warning, "Can't start game bla bla"

**Screenshots**
![grafik](https://user-images.githubusercontent.com/50502395/144717141-2537dce9-e6db-487b-ac3b-ff282c726776.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, 10.0.19043
 - Version: SVN_7272.TC_4884 dx11

**Comment by lukaasm** [comment]
X-Morph feature, should be dropped :)
