### ISSUE TITLE
Button to open tool logs

### ISSUE THREAD

**Issue by Molch1** [exorstudios/riftbreaker-tools#257]
### Enter your feature description.

Like Game logs, a button for each tool to directly open it's latest log file.
Maybe: File->Tools->Level Editor log, etc.

**Comment by lukaasm** [comment]
<img width="408" alt="image" src="https://user-images.githubusercontent.com/48881/205400568-5b2dbce9-006d-4853-86cc-f488e6dc9aaf.png">
