### ISSUE TITLE
Bad UX when having too many mods in dev

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#266]
### How are you using the tools?

Github download

### Enter your bug description.

When having too many mods in development, the workspace editor shortens them too much that you cant even read anything from their names. There also doesn't seem to be any arrows for left + right if there would be even more mods

![grafik](https://user-images.githubusercontent.com/50502395/204769529-2d017697-50ef-4fda-8f9a-88330146b354.png)

Suggestion:
- Show max 10 (?) mods so they name is bigger
- Add arrows for left + right scrolling

### How can this bug be reproduced?

Have many local mods in development

### Tool version

TC_5378

**Comment by SenorRagequit** [comment]
With a smaller workspace area even worse lmao
![grafik](https://user-images.githubusercontent.com/50502395/204769960-159ab9df-16c3-44ae-97df-c2be959a9184.png)

**Comment by lukaasm** [comment]
Tabs no longer resize, but if there is not enough space for all of them, overflow menu will be shown:
<img width="327" alt="image" src="https://user-images.githubusercontent.com/48881/205400697-aba71ba7-d91e-4c9b-91a6-95be6b42ce9a.png">
