### ISSUE TITLE
Bad WS name accepted

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#268]
### How are you using the tools?

Github download

### Enter your bug description.

The naming of the WS editor seems to have been eased by a bit, which leads to some bad possibilities.
Example:
![grafik](https://user-images.githubusercontent.com/50502395/204800575-6bfbe946-11a0-4ee8-9728-5dff7b517652.png)
These are accepted + **even just calling it " " -> Spacebar**

### How can this bug be reproduced?

Create a new workspace, try out ´ . 

### Tool version

TC_5378

**Comment by lukaasm** [comment]
Yeah, anything that windows accepts as folder name is going to be allowed.

I am going to add constraints for starting/ending with whitespace or dot since this is invalid
