### ISSUE TITLE
Show active workspace in overflow menu

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#272]
### Enter your feature description.

As we have an indicator about our active workspace in the tab:
![grafik](https://user-images.githubusercontent.com/50502395/205434067-817251a2-7478-4aa2-9bc0-859a8b3bb001.png)

Also show it in the overflow menu, as we have no idea what WS is active here
![grafik](https://user-images.githubusercontent.com/50502395/205434098-ab0637a1-07bc-420d-a008-a2f54b86721d.png)

**Comment by lukaasm** [comment]
<img width="419" alt="image" src="https://github.com/exorstudios/riftbreaker-tools/assets/48881/5f41f008-b2fb-4c6e-b340-ce6c134a94ab">
