### ISSUE TITLE
Flickering - Level & Model Editor

### ISSUE THREAD

**Issue by Molch1** [exorstudios/riftbreaker-tools#288]
### How are you using the tools?

Github download

### Enter your bug description.

Whenever another menu/dialog window is opened and in foreground, or moved around, Level & Model Editor´s main window starts flickering/producing artifacts in background.

### How can this bug be reproduced?

Open another menu/window so that "main window" is not in focus.

### Tool version

TC_5386

**Comment by lukaasm** [comment]
You have prolly 
```
set render_system dx12
```

in config file baked from old pre-release version. You can change that to dx11.
I will push a fix for old configs
