### ISSUE TITLE
Game reflection - Wrong Type name

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#290]
### How are you using the tools?

Steam

### Enter your bug description.

I don't believe this name is correct
![grafik](https://user-images.githubusercontent.com/50502395/205900335-f3a8d54f-eb67-4730-908f-a69e5a0d38bb.png)

--

![grafik](https://user-images.githubusercontent.com/50502395/205900263-ef3bb7db-f1cd-4b5b-99a9-b9d855cae0fa.png)

### How can this bug be reproduced?

Open the game reflections

### Tool version

TC_5390

**Comment by lukaasm** [comment]
It is :P But I should filter out container types there since they are byproducts and  doesn't matter

**Comment by SenorRagequit** [comment]
+ encoded names
