### ISSUE TITLE
Fallout after using types from game dll

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#293]
### How are you using the tools?

Steam

### Enter your bug description.

Asserts when opening the WS game reflection
![grafik](https://user-images.githubusercontent.com/50502395/206233068-10e5be0f-435d-47dd-adc9-e1e365d1e24d.png)

### How can this bug be reproduced?

Open the game reflection

### Tool version

TC_5395

**Comment by lukaasm** [comment]
Same for render_system, empty value is default DX11 which is fine
