### ISSUE TITLE
PlayGame mission select freezing up having too many workspaces

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#301]
### How are you using the tools?

Steam

### Enter your bug description.

The whole WS editor freezes up for 30 seconds trying to show me the available mission for the mission selection.
![grafik](https://user-images.githubusercontent.com/50502395/207461858-9264b561-ce23-48dc-a90f-ec775184e45b.png)

![grafik](https://user-images.githubusercontent.com/50502395/207461999-e9840928-c6a1-4c7f-ac21-acad0a3d3d6d.png)

Taking a look at the WS editor looks, it seems like it's mounting all of my workspaces which is probably the reason.
![grafik](https://user-images.githubusercontent.com/50502395/207462171-ec8df44c-9328-4db6-8348-efb07dbe229d.png)

### How can this bug be reproduced?

Have many workspaces (with files?)

### Tool version

TC_5395

**Comment by lukaasm** [comment]
https://media.giphy.com/media/EPsdF1SvWrzHy/giphy.gif

**Comment by SenorRagequit** [comment]
Fixed with TC-5410
