### ISSUE TITLE
Auto create autoexec lua

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#303]
### Enter your feature description.

Would be a small handy feature if we could right-click into our WS window and have an option for "Create autoexec".
It then creates an autoexec file in \lua\ as [NameOfWorkspace]_autoexec.lua.

I don't know if possible, but would be extra handy if it also had inside that autoexec file:

```lua
RegisterGlobalEventHandler("PlayerCreatedEvent", function(evt)

    
end)
```

Like a "quickstart"

**Comment by lukaasm** [comment]
http://mustache.github.io/

Leaving there, as an idea for templates
