### ISSUE TITLE
GUI Editor does not save correctly

### ISSUE THREAD

**Issue by MisterSerji** [exorstudios/riftbreaker-tools#310]
### How are you using the tools?

Github download

### Enter your bug description.

The editor saves the edited file much smaller than it should be. This leads to the fact that the interface is no longer visible in the game. However, the function is still given.

### How can this bug be reproduced?

Simply select a file and save it directly. Not even edit it somehow.
The new "mod" is automatically activated at game start and you no longer see the interface that comes with the saved item :(

### Tool version

SVN_8566.TC_5411

**Comment by lukaasm** [comment]
Smaller GUI files are not a bug. 

Interfaces not being visible is probably caused by different engine versions used for tools compilation and currently used in the public game release.
