### ISSUE TITLE
Refresh

### ISSUE THREAD

**Issue by Molch1** [exorstudios/riftbreaker-tools#317]
### Enter your feature description.

A hotkey and/or button like respawn prefabs in Level Editor to quickly refresh/reload entity after making changes, assigning new effects, etc.

**Comment by lukaasm** [comment]
<img width="352" alt="image" src="https://user-images.githubusercontent.com/48881/219026996-a7d2ce48-e11b-4642-b939-84139907e91e.png">
or key F5
