### ISSUE TITLE
Workspace editor - Darkmode

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#32]
**Is your feature request related to a problem? Please describe.**
White is bright.

**Describe the solution you'd like**
Make it dark ⚫ so eyes don't hurt at night.
Everything needs a darkmode!

**Comment by lukaasm** [comment]
![image](https://user-images.githubusercontent.com/48881/155348399-ffc4d74b-fd5d-47b6-8059-35075e795e79.png)
![image](https://user-images.githubusercontent.com/48881/155348620-ea689043-ac05-4d26-93c8-7426a0bad2b2.png)
