### ISSUE TITLE
Special Characters not supported in Manifest Editor

### ISSUE THREAD

**Issue by piisfun** [exorstudios/riftbreaker-tools#320]
### How are you using the tools?

Github download

### Enter your bug description.

Exactly as shown: while you can add additional languages for the description, they aren't actually supported by the tools:

![Screenshot 2023-02-04 234109](https://user-images.githubusercontent.com/54460463/216801962-0b864f18-8da8-460a-a669-d71445c4d980.png)

### How can this bug be reproduced?

While editing a manifest, try adding a Chinese, Japanese, or Korean translation

### Tool version

TC_5411

**Comment by lukaasm** [comment]
It's 'visual', in the sense that you can copy&paste translated text here and upload it and it will work.

Editor is missing fonts to properly display the text ;(
