### ISSUE TITLE
Show advanced steam information regarding used editor with rich_presence

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#326]
Small feature: A way that friends can see what I'm doing in the tools on the friends tab by using the rich_presence steam feature

![grafik](https://user-images.githubusercontent.com/50502395/219208492-2e45449b-8e2e-439e-b0da-4913786da399.png)

workspace editor
model editor
etc.

**Comment by lukaasm** [comment]
<img width="521" alt="image" src="https://user-images.githubusercontent.com/48881/221267250-5f07b49c-aa1a-4043-9983-68587a0f13e2.png">
