### ISSUE TITLE
Crash on opening .pu files

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#335]
### How are you using the tools?

Steam

### Enter your bug description.

When opening such particle files, the model editor crashes
![grafik](https://user-images.githubusercontent.com/50502395/220728962-7c8a5f8e-9b2f-44ce-8d8d-297434232edf.png)

I've send in the crash report

![grafik](https://user-images.githubusercontent.com/50502395/220728883-f1b70468-1ce2-42ab-864e-960e8bc036b5.png)

### How can this bug be reproduced?

If this is bc the particle editor is not really implemented or sth, ignore this issue

### Tool version

TC_5411

**Comment by lukaasm** [comment]
Yup, I will remove opening pu files until done
