### ISSUE TITLE
All editors - Add "Close all tabs" button

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#336]
### Enter your feature description.

Sometimes when opening lots of files and checking back and forth, you are left with many open tabs at the top of the editors.
![grafik](https://user-images.githubusercontent.com/50502395/221431186-4ad18cbc-990f-4323-b66b-09c67f9e9f88.png)

And since many editors support these tabs nowadays, they all need that button.
(Even the GUI editor)

**Comment by lukaasm** [comment]
<img width="274" alt="image" src="https://user-images.githubusercontent.com/48881/221437128-77620b05-4da5-4fbd-b341-20d21bd25a49.png">
Its there in context menu?

**Comment by SenorRagequit** [comment]
Well, today I learned about context menus on the tabs. Who would have guessed (not me)
