### ISSUE TITLE
Tiny world

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#352]
### How are you using the tools?

Github download

### Enter your bug description.

After opening the model editor, it was super zoomed in and had only 1 "biome tile" size of an area.
![grafik](https://user-images.githubusercontent.com/50502395/224848227-d2614f12-f1ae-4e5c-809e-f3d0c05b5be2.png)

### How can this bug be reproduced?

No idea.
Just opened the editor.

### Tool version

TC_5509

**Comment by SenorRagequit** [comment]
APPARENTLY
It's not tiny, but the grid just huge AF and my cam broken?
This is the normal lamp entity:
![grafik](https://user-images.githubusercontent.com/50502395/224850328-5130f024-d1f3-4624-9cc4-3a864d1509d3.png)

**Comment by Molch1** [comment]
Same issue for me and the left section is too narrow by default.

![ModelEditorScaling](https://user-images.githubusercontent.com/97815025/225108954-c9f0abc3-6131-4cbf-a2b7-7b2aa6425a9c.png)

**Comment by SenorRagequit** [comment]
Fixed with TC_5514
