### ISSUE TITLE
Show entity trigger radius

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#357]
### Enter your feature description.

Triggers are often used to trigger for player contact, but I don't think we can visualize the actual trigger size on the entity yet.

F.e:
```lua
TriggerDesc
{
	tag 		"trigger_mod_tag"
	owner 		"parent"
	collision 	"building|building_small|ground_unit"

	Filters
	{
		TeamTriggerFilter 
		{
			team		"player"
		}
		InvisibleTriggerFilter
	}

	Shapes
	{
		PhysicsBoxShape
		{
			x "5.0"
			y "5.0"
			z "5.0"
		}
	}
}
```

So now in the model editor, would be cool if we could activate that and have some red bubble appear around the base unit, showing the radius with the name on it.
**Also**: We might add the trigger as a child, so some kind of check if the child is "just" the trigger so in the model editor it shows the base unit + this trigger radius child. Otherwise it will just show a bubble without the base entity.

**Comment by lukaasm** [comment]
![image](https://github.com/exorstudios/riftbreaker-tools/assets/48881/7372c0ca-d379-48cf-a5c2-3b4125ea71f7)
![image](https://github.com/exorstudios/riftbreaker-tools/assets/48881/3075e6ac-172e-4e8b-8680-15813bcddb79)
![image](https://github.com/exorstudios/riftbreaker-tools/assets/48881/67c52531-4255-4e2a-8405-1146a5bb7c68)
<img width="328" alt="image" src="https://github.com/exorstudios/riftbreaker-tools/assets/48881/e033cc62-a927-48d6-8435-c3be9ee5a147">
