### ISSUE TITLE
Translation file garbled

### ISSUE THREAD

**Issue by STAR-KY-XH** [exorstudios/riftbreaker-tools#369]
Even with all the fonts in the editor folder installed, I still can't seesimplified Chinese in the Translation file editor, they only show???????
![2](https://user-images.githubusercontent.com/104629740/231290939-6849ad82-8d4d-4b00-b18a-4d19a11aad63.png)
So please add the available simplified Chinese font file, or please support me directly to send to the font file.

[Deng.zip](https://github.com/exorstudios/riftbreaker-tools/files/11205161/Deng.zip)
[Dengb.zip](https://github.com/exorstudios/riftbreaker-tools/files/11205162/Dengb.zip)
[Dengl.zip](https://github.com/exorstudios/riftbreaker-tools/files/11205164/Dengl.zip)
[msyh.zip](https://github.com/exorstudios/riftbreaker-tools/files/11205165/msyh.zip)
[msyhbd.zip](https://github.com/exorstudios/riftbreaker-tools/files/11205166/msyhbd.zip)
[msyhl.zip](https://github.com/exorstudios/riftbreaker-tools/files/11205168/msyhl.zip)
[simfang.zip](https://github.com/exorstudios/riftbreaker-tools/files/11205169/simfang.zip)
[simhei.zip](https://github.com/exorstudios/riftbreaker-tools/files/11205170/simhei.zip)
[simkai.zip](https://github.com/exorstudios/riftbreaker-tools/files/11205172/simkai.zip)
[simsun.zip](https://github.com/exorstudios/riftbreaker-tools/files/11205173/simsun.zip)
[方正准圆_GBK.zip](https://github.com/exorstudios/riftbreaker-tools/files/11205174/_GBK.zip)

**Comment by lukaasm** [comment]
<img width="707" alt="image" src="https://user-images.githubusercontent.com/48881/232332871-51188451-906c-4819-850f-55a5ae29219b.png">
It will be fixed in next release
