### ISSUE TITLE
Allow side by side for localization

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#384]
### Enter your feature description.

Please add a way to have 2 languages side by side.
Like that, I can have english left and german right and directly translate it without having to hazzle with multiple open files.

**Comment by lukaasm** [comment]
![image](https://github.com/exorstudios/riftbreaker-tools/assets/48881/57325ab9-cdaf-42d7-814b-b9aa7762ff89)
