### ISSUE TITLE
Show drop down button by default

### ISSUE THREAD

**Issue by Molch1** [exorstudios/riftbreaker-tools#390]
### Enter your feature description.

Drop down button appears too late:

![dropdown_02](https://github.com/exorstudios/riftbreaker-tools/assets/97815025/39f2d7bf-bfb4-4dcf-9f66-c998f0a6cb7e)

Since it's a small button, maybe it should be shown by default?

**Comment by lukaasm** [comment]
<img width="720" alt="image" src="https://github.com/exorstudios/riftbreaker-tools/assets/48881/b1e0e041-11fe-4293-8bc6-623475cf9620">

**Comment by Molch1** [comment]
Very nice!
