### ISSUE TITLE
Show trigger size + shape

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#414]
### Enter your feature description.

Some entities got Triggers (as a child f.e) 
```lua
	children
	{
		EntityBlueprint
		{
		    name "buildings/defense/wall_gate/trigger"

			AttachmentDesc
			{
				attachment "att_door"
			}

			TriggerDesc
			{
				owner 		"parent"
				type		"GRID"

				collision 	"character"
				Shapes
				{
					PhysicsSphereShape
					{
						r "6"
					}
				}
			}
		}
```

and it would be very handy to see that size + shape in the model editor.
Maybe as a new button on the side, like we got with Physics stuff.
![grafik](https://github.com/exorstudios/riftbreaker-tools/assets/50502395/1536eeac-702b-4e9f-9790-749e2730a819)

**Comment by lukaasm** [comment]
Duplicate #357
