### ISSUE TITLE
Level editor - Streamline the naming

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#42]
**Is your feature request related to a problem? Please describe.**
Too confusing, too many differences

**Describe the solution you'd like**
The naming should be streamlined.
You start the level editor, here it shows a small window with the title "Open >> level <<" and on the left, you can choose 
the >> Tiles <<
Clicking the menu option "File" top left offers the ability to create a new >> Tile << or >> Mission <<
When clicking File -> new -> mission it shows a small window with the title "Create >> Map <<"

So now we got Tile, map, mission, level.
Tile is ok, but Map/Mission/Level?
Is there a difference? If not, then the naming should be the same everywhere.

**Comment by lukaasm** [comment]
Some of that is leftovers from X-Morph, but you are right.

Generally, everything edited by LevelEditor right now is a tile.

`New -> Mission` here is a convenience helper that speeds up the initial setup for the "standalone" map creation.
What it does ( and this info should be included in dialogue ):

1.  Creates a unique biome for you
2.  Creates an initial tile with the requested size which is attached to the biome
3.  Creates ".mission" file for you with map size set to your tile size, and tile_spawn_rules with reference to your tile and default survival gameplay rules attached
4. In the future it will create a ".campaign" file for you where you will be able to change ".research"/".loot"  table references
