### ISSUE TITLE
Bugged EditorColumnState wrt Modded Crafting Table

### ISSUE THREAD

**Issue by WirawanMYT** [exorstudios/riftbreaker-tools#422]
### How are you using the tools?

Steam

### Enter your bug description.

Made a custom partial crafting_table.dat. Did some changes on the file. Loaded it Crafting Editor. Changes in partial table showed on original base game file load. Closed default file load and opened modded crafting table. Editor suggested to re-add removed base game EditorColumnState on the file.

### How can this bug be reproduced?

1. Create custom crafting_table.dat with some modded entries.
2. Delete existing specimens' EditorColumnState indices.
3. Open Crafting Editor.
4. Close default table and open modded crafting table.

### Tool version

SVN_8865.TC_5682

**Comment by jerr045** [comment]
It seems like you're referring to an issue or error related to a "Bugged EditorColumnState" in the context of a[ modded version](https://shadowfightapps.com/shadow-fight-4-mod-apk/) crafting table. Without specific details or error messages, it's challenging to provide a precise solution. However, I can offer some general advice on how to approach and troubleshoot such issues in modded Minecraft.

**Comment by tec655** [comment]
Ensure that the mods you are using are compatible with each other and with the version of Minecraft you are playing. Some mods may have conflicts that result in unexpected errors.
Update Mods:

Make sure that all the mods you are using, including the mod adding the crafting table, are up to date. Developers frequently release updates to address bugs and improve compatibility.
Review Mod Documentation:

Check the documentation provided by the mod authors. They may have a knowledge base, FAQs, or community forums where similar issues are discussed, and solutions or workarounds are provided.
Report the Issue:

If you can't find a solution, consider reporting the issue to the mod authors. They may not be aware of the problem, and your feedback can help them address it in future updates.
Check for Mod Configurations:

Some mods allow you to configure their behavior using configuration files. Check the mod's configuration options to see if there are settings related to crafting tables or column states.
Disable Mods Temporarily:

Temporarily disable mods one by one and test your game to identify if a specific mod is causing the issue. This process can help you isolate the problematic mod.
