### ISSUE TITLE
Level editor - Edge texture not paintable 

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#44]
**Describe the bug**
The texture right at the edge of a tile can't be painted. Thus creating ugly artifacts of the biome texture.

**To Reproduce**
1. Create tile
2. Try painting the border

**Expected behavior**
Being able to texture paint it

**Screenshots**
Example: Green biome texture + sand blend texture. Can't paint over the green
![grafik](https://user-images.githubusercontent.com/50502395/144893710-2b173f4e-16f7-48e5-bb40-4aeae7dc64ba.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, 10.0.19043
 - Version: SVN_7272.TC_4884 dx11

**Comment by lukaasm** [comment]
Map generator takes multiple tiles, rotates them and puts them together matching them by edge type.

We must enforce that edges that are glued together are always the same ( height/blending/material ) that is why the tile edge editing is locked.

Currently, the editor exposes to you only the "default" edge type which is what you see.

But there is a feature ( only missing editor UI part ) that allows change/create a new type of edge on a tile but introducing more edge types to the generator increases the number of required tile permutations substantially that is why the feature was not expanded further.
