### ISSUE TITLE
Level editor - Add warning for used & unsaved biome textures

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#49]
**Is your feature request related to a problem? Please describe.**
I lost work as I didn't know that the biome textures need to be saved separately. 

**Describe the solution you'd like**
When the user is using biome textures which have not yet been saved in the biome side menu, show a warning.
"Unsaved biome textures, please save ... bla bla"
Just so the user knows that it doesn't get saved automatically when pressing CTRL + S or save.

**Comment by lukaasm** [comment]
<img width="492" alt="image" src="https://user-images.githubusercontent.com/48881/235309883-3a574497-2559-4c02-8359-90d213a52f36.png">
