### ISSUE TITLE
Workspace editor - Workspace diff

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#5]
**Is your feature request related to a problem? Please describe.**
No

**Additional context**
Would be cool to have a diff feature for workspaces.
You can click a button that shows the workspaces and a little checkbox behind.
Activating that checkbox adds the workspace to the "diff overview screen" - you can select 2 workspaces max.
That "diff overview screen" shows the selected workspaces next to another and highlights differences.
Maybe as a first step, just highlight folders/files and not the exact line number INSIDE a file.
Just to get a better overview about what's different.

**Comment by lukaasm** [comment]
Can you give me an example / epic paint design art how do you see it, so it is usable? Cause all I see is:

<img width="532" alt="image" src="https://user-images.githubusercontent.com/48881/206525992-a6e6db91-f6f3-4aab-838e-5ea6d200b687.png">
And I don't know if that is the thing you want?

**Comment by lukaasm** [comment]
Ok, for now it will be simple file tree structure comparison
![image](https://user-images.githubusercontent.com/48881/206562161-b2ecd9b9-bc37-4aaa-976c-be39dacc6bf6.png)

**Comment by lukaasm** [comment]
https://github.com/cubicdaiya/dtl

Leaving for myself, library for creating diffs between files.
