### ISSUE TITLE
Level editor - Add graphics options

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#53]
**Is your feature request related to a problem? Please describe.**
My pc is too bad

**Describe the solution you'd like**
A small graphics menu would be handy.
Just some options like low/medium/high so not every texture is ultra 4k UHD max premium.
Especially when starting the general layout not every entity needs to be high res, so it could save some FPS

**Comment by lukaasm** [comment]
Tracked by:
https://github.com/exorstudios/riftbreaker-tools/issues/229
