### ISSUE TITLE
Level editor - Scene search clear button

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#55]
**Describe the solution you'd like**
Always having to manually delete the word you searched in the scene editor gets tedious, it would be great to have a "clear" button which removes the search words.
Example:
![grafik](https://user-images.githubusercontent.com/50502395/145193202-9ca390e6-3087-4a8e-a81f-230f2952ed63.png)

**Comment by lukaasm** [comment]
![image](https://user-images.githubusercontent.com/48881/149122850-3ed50b6b-d263-4d2f-8f9f-4dba22e0f992.png)
