### ISSUE TITLE
Level editor - Add rotate as group

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#56]
**Is your feature request related to a problem? Please describe.**
Rotating multiple selected objects turns them one by one by the rotation degree

**Describe the solution you'd like**
When having selected multiple entities, we need an option to rotate them as a group.
So when we use the rotate tool, not every single entity gets rotated, but the whole group gets rotated around the groups middle.

Example:
![grafik](https://user-images.githubusercontent.com/50502395/145284145-26e710eb-4f0a-494b-ab1c-a99d6cbe4537.png)

**Comment by lukaasm** [comment]
This is already a feature.
You need to change gizmo to "World" transformation [mode]
![2021-12-09-08-54-48](https://user-images.githubusercontent.com/48881/145356717-f6cf9ac9-5283-48b4-af3d-e7fa125fcf3b.gif)

**Comment by SenorRagequit** [comment]
![ ](https://media.giphy.com/media/3oriOfixsKjISS9kR2/giphy.gif)
