### ISSUE TITLE
Mission editor - Add a "last worked on" screen on startup

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#58]
**Describe the solution you'd like**
Like the level editor, the mission editor could have a screen popping up showing the last logic files you worked on in that workspace. So you can quickly choose the one you want to keep on working.

**Comment by lukaasm** [comment]
![image](https://user-images.githubusercontent.com/48881/180764254-5cf24522-427b-49ae-bfc2-af629c06fc38.png)
