### ISSUE TITLE
Level editor - [Steam] Unable to start the Riftbreaker from within

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#61]
**Describe the bug**
When starting the Riftbreaker tools [Steam] and trying to play test the map, the start of The Riftbreaker stops and it shows:
![grafik](https://user-images.githubusercontent.com/50502395/146459910-1de1e4ee-04ea-4627-9b15-416de974aa20.png)

**To Reproduce**
1. Start the RB tools on Steam
2. Start the level editor
3. Use some map
4. Click the button to play test the map

**Expected behavior**
The Riftbreaker opening up

**Screenshots**
![grafik](https://user-images.githubusercontent.com/50502395/146459996-5d81e9a5-2856-42bf-99ad-359b866aab6b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, 10.0.19043
 - Version: SVN_7272.TC_4884 dx11
 - Steam

**Comment by lukaasm** [comment]
Seems like steam doesn't like to launch applications from different SKU's. Some workaround will be needed :)
