### ISSUE TITLE
Level Editor - not working after playing standalone map via play button

### ISSUE THREAD

**Issue by Molch1** [exorstudios/riftbreaker-tools#69]
**Describe the bug**
After playing a Mission(Standalone Map) via play button Level Editor is not functioning correctly anymore. 
While moving around with camera works,  you cant select or place entities - Level Editor needs to be restarted.

**To Reproduce**

1. Open Level Editor 
2. Jump in map via Play button
3. close map
4. go back to level editor
5. Level Editor not working correctly anymore.

**Expected behavior**
Level Editor working normally.

**Desktop (please complete the following information):**
 - OS: Win10 Pro 10.0.19042
 - Steam

**Comment by lukaasm** [comment]
The same as #15 fix will be included in the next milestone release next week.
