### ISSUE TITLE
Add new service: StatisticsService 

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#86]
**Is your feature request related to a problem? Please describe.**
A simple service like "StatisticsService" would be nice to have. Currently, it isn't easily possible to get global values for stuff.

**Additional context**
Examples:
StatisticsService:GetCountKilledEnemies
StatisticsService:ResetCountKilledEnemies

StatisticsService:GetCountMinedResources
StatisticsService:ResetCountMinedResources

StatisticsService:GetCountWalkDistance
StatisticsService:ResetCountWalkDistance

StatisticsService:GetCountBuiltBuildings
StatisticsService:ResetCountBuiltBuildings

StatisticsService:GetCountPlayerDeaths
StatisticsService:ResetCountPlayerDeaths  
  
This would be very simple to use, so we can connect those results to some cool events.
When int of StatisticsService:GetCountKilledEnemies > 10 unlock Skin
When int of StatisticsService:GetCountMinedResources > 100.000 spawn additional storage as some "Mission complete" quest.
When int of StatisticsService:GetCountPlayerDeaths > 1 write text "Git gud"  

Stuff like that.

**Comment by lukaasm** [comment]
https://github.com/exorstudios/riftbreaker-lua-utils/blob/main/lua/services/playstats_utils.lua

Fixed by @SenorRagequit
