### ISSUE TITLE
Workspace editor - Show mod size

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#9]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A small information text showing the current size of the mod you are working on.
As an example, the size could be shown where the button for "Set active" is (Wouldn't work for not active workspaces then though....)

![PaintDotNet_2021-12-03_20-43-49](https://user-images.githubusercontent.com/50502395/144663652-ab5a4227-90fa-41fa-9d77-11547086b12b.png)

**Comment by lukaasm** [comment]
<img width="334" alt="image" src="https://user-images.githubusercontent.com/48881/205396176-3b576ace-b891-4767-81f9-1fafdcc84d4b.png">
