### ISSUE TITLE
Model editor - Add fast switch between entities inside one entity blueprint file

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#90]
**Is your feature request related to a problem? Please describe.**
Having to manually search for the correct entity is very tedious.

**Describe the solution you'd like**
When having the window of the blueprints open, add hotkeys like w/s to quickly switch between entities in the list.
Example:
I opened the lights/point/ entity file and it has many smaller entities in it.
It would be helpful if I could just scroll the list with w/s to search for a specific light.
![grafik](https://user-images.githubusercontent.com/50502395/156794484-8348c7d8-4596-4dc8-b342-d72fab332185.png)
Currently, you have to manually close open every single one - which is fine for normal entities, but bigger ones like lights or effects are tedious to work with.

**Comment by lukaasm** [comment]
You mean, keyboard navigation? Up/Down ?

**Comment by SenorRagequit** [comment]
Yes.
Pressing W would select the next entity up, pressing S would select the next entity down.
So you can quickly smash S or W to scroll the list and just watch the entity to see what it looks like.
