### ISSUE TITLE
Model editor - Weird GUI components behavior

### ISSUE THREAD

**Issue by SenorRagequit** [exorstudios/riftbreaker-tools#95]
**Describe the bug**
When using the model editor, you can open the blueprint tab on the side of the entity you are looking at.
In there are different components which are like headers you can expand by clicking on.
But the whole behavior around them is super weird.
I click on f.e the "AnimationGraphDesc" and it directly opens the side menu of the animation graph.
But it also expands itself and re-structures the layout of the Blueprint page as it pushes in the dots below it.
So when you want to expand it you click on it, it automatically switches the window and you have to get back to the blueprint page to see what happened.

**To Reproduce**
1. Open model editor
2. Click on animationgraphdesc / skeletondesc

**Expected behavior**
Either they don't look like headers which unfold to show more information and more like a "open that sidemenu from here" button or they JUST unfold/extend to show more information and dont automatically switch scenes.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/50502395/157202366-8a896dd0-b55d-4466-a9dd-57b03f070dd9.png)

Video: https://streamable.com/dzhza5

**Desktop (please complete the following information):**
Steam
Tools v. 4950

**Comment by lukaasm** [comment]
![image](https://user-images.githubusercontent.com/48881/157302340-4e8bec62-099b-4b25-a6e8-d38dca6bb77a.png)
DOT + Tooltip
